[package]
name = "arch"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { path = "../config" }

riscv = "0.13"
sbi-rt = "0.0.3"

[features]
default = ["irq"]
# Kernel interrupt
irq = []
