[package]
name = "sync"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-utils = { path = "../../crates/async-utils/" }

log = "0.4"
riscv = "0.13"
